# Generated by Django 3.1.7 on 2021-09-15 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0002_remove_product_url_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='user',
        ),
    ]
